name       : imlib2
version    : 1.5.1
release    : 5
source     :
    - https://kent.dl.sourceforge.net/project/enlightenment/imlib2-src/1.5.1/imlib2-1.5.1.tar.bz2 : fa4e57452b8843f4a70f70fd435c746ae2ace813250f8c65f977db5d7914baae
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Fast graphics manipulation library
description: |
    Imlib2 is a graphics library for fast file loading, saving, rendering and manipulation.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - giflib-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
