name       : imlib2
version    : 1.4.9
release    : 3
source     :
    - http://internode.dl.sourceforge.net/project/enlightenment/imlib2-src/1.4.9/imlib2-1.4.9.tar.bz2 : 7d2864972801823ce44ca8d5584a67a88f0e54e2bf47fa8cf4a514317b4f0021
license    : GPL-2.0+
component  : desktop.library
summary    : Fast graphics manipulation library
description: |
    Imlib2 is a graphics library for fast file loading, saving, rendering and manipulation.
builddeps  :
    - pkgconfig(libpng15)
    - pkgconfig(libtiff-4)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - giflib-devel
    - libjpeg-turbo-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
