name       : imlib2
version    : 1.6.1
release    : 6
source     :
    - https://sourceforge.net/projects/enlightenment/files/imlib2-src/1.6.1/imlib2-1.6.1.tar.bz2 : 4d393a77e13da883c8ee2da3b029da3570210fe37d000c9ac33d9fce751b166d
license    : GPL-2.0-or-later
component  : desktop.library
summary    : Fast graphics manipulation library
description: |
    Imlib2 is a graphics library for fast file loading, saving, rendering and manipulation.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - pkgconfig(x11)
    - pkgconfig(xext)
    - giflib-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
